Step 1: statistic service
dimabakinec/java-explore-with-me pull request #1
Opened 2023-07-15 10:02 UTC by dimabakinec

2023-07-18 21:01 UTC, alexache requested changes

2023-07-18 21:01 UTC, alexache commented on stats-service/client/src/main/java/ru/practicum/StatsClient.java
> +                        .queryParam("uris", uris)
Это не совсем правильный способ, нужно переделать список в строку, где значения перечислены через запятую

2023-07-18 21:01 UTC, alexache commented on stats-service/server/src/main/java/ru/practicum/controller/StatController.java
> +    private void validateDate(LocalDateTime start, LocalDateTime end) {
Приватные методы нужно писать после публичных

2023-07-18 21:01 UTC, alexache commented on stats-service/server/src/main/java/ru/practicum/model/StatSvc.java
> +@Data
@Equals/hashcode плохо работает с JPA моделями

2023-07-19 08:30 UTC, dimabakinec commented on stats-service/server/src/main/java/ru/practicum/controller/StatController.java
> +    private void validateDate(LocalDateTime start, LocalDateTime end) {
fixed

2023-07-19 08:45 UTC, dimabakinec commented on stats-service/server/src/main/java/ru/practicum/model/StatSvc.java
> +@Data
fixed

2023-07-19 11:38 UTC, dimabakinec commented on stats-service/client/src/main/java/ru/practicum/StatsClient.java
> +                        .queryParam("uris", uris)
fixed, если я правильно понял наставника

2023-07-20 14:02 UTC, alexache approved these changes

2023-07-20 14:02 UTC, alexache commented on stats-service/server/src/main/java/ru/practicum/controller/StatController.java
> +    private final StatService service;
Речь была только про приватные методы, поля же пишутся до всех методов

2023-07-20 16:18 UTC, dimabakinec commented on stats-service/server/src/main/java/ru/practicum/controller/StatController.java
> +    private final StatService service;
fixed

2023-07-20 16:23 UTC, merged