Step 2: main service
dimabakinec/java-explore-with-me pull request #2
Opened 2023-07-21 08:32 UTC by dimabakinec

2023-07-25 22:02 UTC, alexache requested changes

2023-07-25 22:02 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/compilations/model/Compilation.java
> +@EqualsAndHashCode
Нельзя использовать эту аннотацию на JPA моделях

2023-07-25 22:02 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/categories/service/CategoryServiceImpl.java
> +            throw new ValidateException("The category is not empty");
А если ошибка по какой-то другой причине? Отсутствие коннекта к базе, например? Может лучше явно проверять количество событий с такой категорией перед удалением?

2023-07-25 22:02 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/events/controllers/PublicEventController.java
> +        log.info("client ip: {}", request.getRemoteAddr());
Похоже на отладочные логи

2023-07-25 22:02 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/events/controllers/PublicEventController.java
> +                onlyAvailable, sortParam, from, size, request);
Почему бы не передать только адрес и айпи в метод сервиса?

2023-07-25 22:02 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/events/dto/EventFullDto.java
> +    AdditionalEventInformation eventInformation;
Модификатор доступа?

2023-07-25 22:02 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/events/model/Event.java
> +@EqualsAndHashCode(onlyExplicitlyIncluded = true)
Лишняя аннотация

2023-07-25 22:02 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/events/model/Event.java
> +    private Integer confirmedRequests = 0; // Количество одобренных заявок на участие в данном событии;
Это не должно храниться в таблице событий

2023-07-25 22:02 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/events/repository/EventRepository.java
> +    @Query(
Нельзя ли сделать такой запрос через название метода?

2023-07-25 22:02 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/requests/service/RequestServiceImpl.java
> +    private void validParticipantLimit(Event event) {
Сначала должны идти публичные методы, а уже потом приватные

2023-07-25 22:02 UTC, alexache commented on ewm-service/src/main/resources/schema.sql
> +  confirmed_requests int,
Лишнее поле

2023-07-25 22:02 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/events/service/EventServiceImpl.java
> +            events = getEventsBeforeRangeEnd(events, rangeEnd);
Почему бы это не сделать частью запроса к базе?

2023-07-25 22:02 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/events/service/EventServiceImpl.java
> +            events = eventRepository.findAllPublishStateOnlyNotAvailable(state, getRangeStart(rangeStart), categories,
Не перепутаны ли if и else местами?

2023-07-25 22:02 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/events/service/EventServiceImpl.java
> +            events = eventRepository.findAllPublishStateOnlyNotAvailable(state, getRangeStart(rangeStart), categories,
И для доступности нужно проверять? есть ли еще места (при наличии лимита)

2023-07-26 06:53 UTC, dimabakinec commented on ewm-service/src/main/java/ru/practicum/compilations/model/Compilation.java
> +@EqualsAndHashCode
fixed

2023-07-26 06:55 UTC, dimabakinec commented on ewm-service/src/main/java/ru/practicum/events/model/Event.java
> +@EqualsAndHashCode(onlyExplicitlyIncluded = true)
fixed

2023-07-26 06:59 UTC, dimabakinec commented on ewm-service/src/main/java/ru/practicum/requests/service/RequestServiceImpl.java
> +    private void validParticipantLimit(Event event) {
fixed

2023-07-26 08:22 UTC, dimabakinec commented on ewm-service/src/main/java/ru/practicum/events/dto/EventFullDto.java
> +    AdditionalEventInformation eventInformation;
fixed

2023-07-26 09:20 UTC, dimabakinec commented on ewm-service/src/main/java/ru/practicum/events/controllers/PublicEventController.java
> +        log.info("client ip: {}", request.getRemoteAddr());
fixed

2023-07-26 11:12 UTC, dimabakinec commented on ewm-service/src/main/java/ru/practicum/categories/service/CategoryServiceImpl.java
> +            throw new ValidateException("The category is not empty");
fixed

2023-07-27 07:30 UTC, dimabakinec commented on ewm-service/src/main/java/ru/practicum/events/controllers/PublicEventController.java
> +                onlyAvailable, sortParam, from, size, request);
это обязательно делать? на что это влияет?

2023-07-27 07:31 UTC, dimabakinec commented on ewm-service/src/main/resources/schema.sql
> +  confirmed_requests int,
этого нет в задании, как это нужно сделать? все делают же именно так?!

2023-07-27 07:32 UTC, dimabakinec commented on ewm-service/src/main/java/ru/practicum/events/model/Event.java
> +    private Integer confirmedRequests = 0; // Количество одобренных заявок на участие в данном событии;
а где это должно быть? этого нет в задании, как это нужно сделать? все делают же именно так?!

2023-07-27 07:37 UTC, dimabakinec commented on ewm-service/src/main/java/ru/practicum/events/service/EventServiceImpl.java
> +            events = getEventsBeforeRangeEnd(events, rangeEnd);
я не понимаю как это это можно сделать?

2023-07-27 07:38 UTC, dimabakinec commented on ewm-service/src/main/java/ru/practicum/events/service/EventServiceImpl.java
> +            events = eventRepository.findAllPublishStateOnlyNotAvailable(state, getRangeStart(rangeStart), categories,
нет, if else не перепутаны. это обязательно делать?

2023-07-27 07:38 UTC, dimabakinec commented on ewm-service/src/main/java/ru/practicum/events/repository/EventRepository.java
> +    @Query(
а как это правильно сделать? и почему нельзя так оставить?

2023-07-27 18:49 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/events/repository/EventRepository.java
> +    @Query(
Меньше кастомных запросов - меньше ошибок

2023-07-27 18:49 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/events/controllers/PublicEventController.java
> +                onlyAvailable, sortParam, from, size, request);
Это влияет на меньшую связность классов и более чистый дизайн

2023-07-27 18:49 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/events/model/Event.java
> +    private Integer confirmedRequests = 0; // Количество одобренных заявок на участие в данном событии;
Есть таблица запросов, из нее можно получать количество подтвержденных заявок определенных событий.
Если все делают так, то все будут переделывать, потому что такое решение не примут

2023-07-27 18:54 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/events/repository/EventRepository.java
> +    @Query(
findByInitiator_Id(Long userId) ?

2023-07-27 18:54 UTC, alexache commented on ewm-service/src/main/resources/schema.sql
> +  confirmed_requests int,
Это проистекает из того, что это излишнее дублирование информации с потенциальными проблемами из-за race conditions и прочего, поэтому лучше избегать. Есть таблица с заявками, можно к ней формировать запрос для получения количества подтвержденных заявок по событию или списку событий (обязательно избегать запросов к базе в цикле)

2023-07-27 18:56 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/events/service/EventServiceImpl.java
> +            events = eventRepository.findAllPublishStateOnlyNotAvailable(state, getRangeStart(rangeStart), categories,
Да, это важная правка

2023-07-27 19:13 UTC, alexache requested changes

2023-07-27 19:13 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/events/controllers/PublicEventController.java
> +        log.debug("client ip: {}", request.getRemoteAddr());
Все еще можно бы подсократить количество лог записей, много "шума"

2023-07-27 19:13 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/events/controllers/PublicEventController.java
> +        log.debug("client ip: {}", request.getRemoteAddr());
Все еще можно бы подсократить количество лог записей, много "шума"

2023-07-28 07:22 UTC, dimabakinec commented on ewm-service/src/main/java/ru/practicum/events/controllers/PublicEventController.java
> +        log.debug("client ip: {}", request.getRemoteAddr());
не понял, совсем нужно убрать? у меня сейчас .info вообще нет

2023-07-28 10:16 UTC, dimabakinec commented on ewm-service/src/main/java/ru/practicum/events/repository/EventRepository.java
> +    @Query(
fixed

2023-07-29 18:42 UTC, dimabakinec commented on ewm-service/src/main/java/ru/practicum/events/controllers/PublicEventController.java
> +                onlyAvailable, sortParam, from, size, request);
fixed

2023-07-30 18:56 UTC, dimabakinec commented on ewm-service/src/main/java/ru/practicum/events/service/EventServiceImpl.java
> +            events = getEventsBeforeRangeEnd(events, rangeEnd);
fixed

2023-07-30 19:49 UTC, dimabakinec commented on ewm-service/src/main/java/ru/practicum/events/service/EventServiceImpl.java
> +            events = eventRepository.findAllPublishStateOnlyNotAvailable(state, getRangeStart(rangeStart), categories,
с названиями решили, поменял названия местами для правильной логики

2023-08-03 17:12 UTC, dimabakinec commented on ewm-service/src/main/java/ru/practicum/events/controllers/PublicEventController.java
> +        log.debug("client ip: {}", request.getRemoteAddr());
исправлено на debug

2023-08-04 16:32 UTC, dimabakinec commented on ewm-service/src/main/java/ru/practicum/events/controllers/PublicEventController.java
> +        log.debug("client ip: {}", request.getRemoteAddr());
наставник сказала сделать debug

2023-08-04 16:32 UTC, dimabakinec commented on ewm-service/src/main/java/ru/practicum/events/service/EventServiceImpl.java
> +            events = eventRepository.findAllPublishStateOnlyNotAvailable(state, getRangeStart(rangeStart), categories,
fixed

2023-08-04 16:33 UTC, dimabakinec commented on ewm-service/src/main/resources/schema.sql
> +  confirmed_requests int,
fixed

2023-08-04 16:33 UTC, dimabakinec commented on ewm-service/src/main/java/ru/practicum/events/model/Event.java
> +    private Integer confirmedRequests = 0; // Количество одобренных заявок на участие в данном событии;
fixed

2023-08-05 10:51 UTC, alexache approved these changes

2023-08-05 10:51 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/events/service/EventServiceImpl.java
> +            eventFullDto.setConfirmedRequests(requestRepository.getConfirmedRequestsByEventId(event.getId()));
Это запрос к базе внутри цикла по событиям. Такое точно нужно избегать и переделывать в запрос сразу по списку событий

2023-08-05 10:51 UTC, alexache commented on ewm-service/src/main/java/ru/practicum/events/service/EventServiceImpl.java
> +                            eventsParticipantLimit.get(eventShort.getId()) > requestRepository.getConfirmedRequestsByEventId(eventShort.getId())))
Это тоже запрос к базе в цикле, так нельзя. Нужно сначала получить количество подтержденных заявок у событий одним запросом к базе (и затем раскладыванием в мапу, как промежуточное действие)

2023-08-05 15:15 UTC, merged